hexapod_hardware:
  ros__parameters:
    comport: COM4
    fl_coxa_dir: -1
    fl_coxa_offset: -0.1
    fl_femur_dir: 1
    fl_femur_offset: -0.25
    fl_tibia_dir: -1
    fl_tibia_offset: -1.7
    fr_coxa_dir: 1
    fr_coxa_offset: 0.0
    fr_femur_dir: -1
    fr_femur_offset: 0.55
    fr_tibia_dir: 1
    fr_tibia_offset: 1.55
    ml_coxa_dir: -1
    ml_coxa_offset: 0.05
    ml_femur_dir: 1
    ml_femur_offset: -0.4
    ml_tibia_dir: -1
    ml_tibia_offset: -1.05
    mr_coxa_dir: 1
    mr_coxa_offset: -0.5
    mr_femur_dir: -1
    mr_femur_offset: 0.3
    mr_tibia_dir: 1
    mr_tibia_offset: 1.6
    rl_coxa_dir: -1
    rl_coxa_offset: 0.1
    rl_femur_dir: 1
    rl_femur_offset: -0.4
    rl_tibia_dir: -1
    rl_tibia_offset: -1.55
    rr_coxa_dir: 1
    rr_coxa_offset: 0.1
    rr_femur_dir: -1
    rr_femur_offset: 0.3
    rr_tibia_dir: 1
    rr_tibia_offset: 1.4
    use_sim_time: false
